# Generated by Django 4.2 on 2023-04-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of the client', max_length=150)),
                ('email', models.CharField(help_text='email of the client', max_length=150)),
                ('phone', models.CharField(help_text='phone number of the client', max_length=150)),
                ('requirement', models.CharField(help_text='requirement of the client', max_length=150)),
            ],
            options={
                'db_table': 'client_request',
            },
        ),
    ]
